Package everything
tarantool/tarantool-python pull request #248
Opened 2022-10-19 14:13 UTC by DifferentialOrange

2022-11-08 17:01 UTC, LeonidVas requested changes
Hi. Thank you for the patchset.
Great work.

* "Specify explicit Python 3 python3 and pip3 binaries everywhere to make commands more portable." - why does it make commands more portable?

See several comments bellow.

2022-11-09 08:58 UTC, DifferentialOrange commented
> "Specify explicit Python 3 python3 and pip3 binaries everywhere to make commands more portable." - why does it make commands more portable?

`python3` is Python 3 binary for all systems which have Python 3 installed. For some configurations, `python` is `python3` by default, sometimes you can make `python` to be `python3` by installing `python-is-python3` package or by messing with aliases (but I don't think we should enforce users to do so), but there are some systems in which `python` is `python2`. Same goes for `pip` (and I think I've met the case when `python` was `python3` but `pip` was pip for Python 2).

2022-11-09 09:18 UTC, DifferentialOrange commented on .github/workflows/packing.yml
> +        # Checkout all tags for correct version computation
Fixed

2022-11-09 09:19 UTC, DifferentialOrange commented on .github/workflows/packing.yml
> +    runs-on: ubuntu-20.04
Fixed (it's funny that now `ubuntu-latest` is actually `ubuntu-20.04` rather than `ubuntu-22.04`)

2022-11-09 09:19 UTC, DifferentialOrange commented on .github/workflows/packing.yml
> +    runs-on: ubuntu-20.04
Fixed

2022-11-09 09:19 UTC, DifferentialOrange commented on .github/workflows/packing.yml
> +    runs-on: windows-2022
Also used latest just in case

2022-11-09 09:19 UTC, DifferentialOrange commented on .github/workflows/packing.yml
> +        # Checkout all tags for correct version computation
Fixed

2022-11-09 09:19 UTC, DifferentialOrange commented on Makefile
> +.PHONY: rpm-dist-publish
Removed

2022-11-09 09:19 UTC, DifferentialOrange commented on debian/source/options
> +extend-diff-ignore="\.egg-info$"
Fixed

2022-11-09 09:19 UTC, DifferentialOrange commented on .github/workflows/packing.yml
> +        # Checkout all tags for correct version computation
Fixed

2022-11-09 09:44 UTC, LeonidVas approved these changes
LGTM

2022-11-09 10:28 UTC, merged